<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Bella.png" />
    <None Remove="Images\John.png" />
    <None Remove="Images\Smith.png" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
	</ItemGroup>
	
	<ItemGroup>
	  <Resource Include="Images\Bella.png">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\John.png">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\Smith.png">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>
