<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Build\Imports\LicensingConfig.targets" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>GenerateDocuments</RootNamespace>
    <AssemblyName>GenerateDocuments</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />
    <Reference Include="Telerik.Documents.SpreadsheetStreaming">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Documents.SpreadsheetStreaming.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
</Project>