<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Prism.Unity">
      <Version>8.1.97</Version>
    </PackageReference>
    <PackageReference Include="Prism.Wpf">
      <Version>8.1.97</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
</Project>
