<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\1PersonalFolders.png" />
    <Resource Include="images\2DeletedItems.png" />
    <Resource Include="images\3Drafts.png" />
    <Resource Include="images\4Inbox.png" />
    <Resource Include="images\calendarBig.png" />
    <Resource Include="images\contact.png" />
    <Resource Include="images\contactsBig.png" />
    <Resource Include="images\junk.png" />
    <Resource Include="images\letter.png" />
    <Resource Include="images\mailBig.png" />
    <Resource Include="images\outbox.png" />
    <Resource Include="images\sent.png" />
    <Resource Include="images\tasksBig.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\mailSmall.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\contactsSmall.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\calendarSmall.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>