<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ImportExportFromAndToMSProject</RootNamespace>
    <AssemblyName>ImportExportFromAndToMSProject</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.NoXaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="XMLFilesToLoad\HomeMovePlan.xml" />
    <Resource Include="XMLFilesToLoad\MarketSchedule.xml" />
    <Resource Include="XMLFilesToLoad\NursingSchedule.xml" />
    <Resource Include="XMLFilesToLoad\WeddingPlanner.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>