<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build\Imports\LicensingConfig.targets" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />
    <Reference Include="Telerik.Windows.Controls">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Navigation">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.Navigation.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\1_Copy.png" />
    <Resource Include="Images\1_Paste.png" />
    <Resource Include="Images\1_Save.png" />
    <Resource Include="Images\2_AlignCenter.png" />
    <Resource Include="Images\2_AlignLeft.png" />
    <Resource Include="Images\2_AlignMiddle.png" />
    <Resource Include="Images\2_AlignRight.png" />
    <Resource Include="Images\3_ColumnsInsert.png" />
    <Resource Include="Images\3_ColumnsRemove.png" />
    <Resource Include="Images\4_Copy.png" />
    <Resource Include="Images\4_Cut.png" />
    <Resource Include="Images\4_Paste.png" />
    <Resource Include="Images\5_FillDown.png" />
    <Resource Include="Images\5_FillLeft.png" />
    <Resource Include="Images\5_FillRight.png" />
    <Resource Include="Images\5_FillUp.png" />
    <Resource Include="Images\6_FontSizeDecrease.png" />
    <Resource Include="Images\6_FontSizeIncrease.png" />
    <Resource Include="Images\6_ForegroundColor.png" />
    <Resource Include="Images\6_Merge.png" />
    <Resource Include="Images\6_MergeAcross.png" />
    <Resource Include="Images\6_MergeAndCenter.png" />
    <Resource Include="Images\7_Open.png" />
    <Resource Include="Images\7_Save.png" />
    <Resource Include="Images\7_SaveAs.png" />
    <Resource Include="Images\8_ThickBorderBox.png" />
    <Resource Include="Images\8_ThickBottomBorder.png" />
    <Resource Include="Images\8_TopAndBottomBorder.png" />
    <Resource Include="Images\8_TopAndThickBottomBorder.png" />
    <Resource Include="Images\8_TopBorder.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Readme.md" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>