<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build\Imports\LicensingConfig.targets" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Watermark</RootNamespace>
    <AssemblyName>Watermark</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Telerik.Windows.Documents.Core">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.Core.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Flow">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.Flow.dll</HintPath>
    </Reference>
    <PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />
    <Reference Include="Telerik.Windows.Controls">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Input">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.Input.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Navigation">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.RibbonView">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.RibbonView.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.RichTextBoxUI">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.RichTextBoxUI.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.FormatProviders.Html">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.FormatProviders.Html.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.FormatProviders.OpenXml">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.FormatProviders.OpenXml.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.FormatProviders.Pdf">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.FormatProviders.Pdf.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.FormatProviders.Rtf">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.FormatProviders.Rtf.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.FormatProviders.Xaml">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.FormatProviders.Xaml.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Zip">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Zip.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Documents.Proofing.Dictionaries.En-US">
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Documents.Proofing.Dictionaries.En-US.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\telerik-ninja.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>