<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\field_pol.shp" />
    <Resource Include="Resources\grass_pol.shp" />
    <Resource Include="Resources\playground_lin.shp" />
    <Resource Include="Resources\stadium_pol.dbf" />
    <Resource Include="Resources\stadium_pol.shp" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\default.jpg" />
    <Resource Include="Images\stadium_angle_1.jpg" />
    <Resource Include="Images\stadium_angle_2.jpg" />
    <Resource Include="Images\stadium_long_side.jpg" />
    <Resource Include="Images\stadium_short_side.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>