using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using Telerik.Windows.Controls;

namespace AutoGeneratedTag
{
	public partial class Example : UserControl
	{
		LayoutData data;

		public Example()
		{
			InitializeComponent();
			this.XmlTextBox.DataContext = this.data = new LayoutData();
		}

		private string SaveLayoutAsString()
		{
			MemoryStream stream = new MemoryStream();
			this.docking.SaveLayout(stream);

			stream.Seek(0, SeekOrigin.Begin);

			StreamReader reader = new StreamReader(stream);
			return reader.ReadToEnd();
		}

		private void LoadLayoutFromString(string xml)
		{
			using (Stream stream = new MemoryStream(Encoding.UTF8.GetBytes(xml)))
			{
				stream.Seek(0, SeekOrigin.Begin);
				this.docking.LoadLayout(stream);
			}
		}

		private void SaveLayoutButton_Click(object sender, RoutedEventArgs e)
		{
			this.data.Xml = this.SaveLayoutAsString();
			this.LoadLayoutButton.IsEnabled = true;
		}

		private void LoadLayoutButton_Click(object sender, RoutedEventArgs e)
		{
			this.LoadLayoutFromString(this.data.Xml);
		}

		private void AddButton_Click(object sender, RoutedEventArgs e)
		{
			var split = new RadSplitContainer();
			var group = new RadPaneGroup();
			var pane = new RadPane();

			group.Items.Add(pane);
			split.Items.Add(group);
			split.InitialPosition = Telerik.Windows.Controls.Docking.DockState.DockedTop;
			RadDocking.SetIsAutoGenerated(group, true);
			RadDocking.SetIsAutoGenerated(split, true);

			this.docking.Items.Add(split);
		}

		private void RemoveButton_Click(object sender, RoutedEventArgs e)
		{
			this.docking.ActivePane.RemoveFromParent();
		}
	}
}
