<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\DefaultIcons\file32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\DefaultIcons\photos.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\1PersonalFolders.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\2DeletedItems.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\3Drafts.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\4Inbox.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\search.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\beach_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\forest_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\vista_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>