<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build\Imports\LicensingConfig.targets" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />
    <Reference Include="Telerik.Windows.Controls">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Input">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.Input.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Navigation">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.RibbonView">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Controls.RibbonView.dll</HintPath>
    </Reference>
    <Reference Include="Telerik.Windows.Data">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(TELERIKWPFDIR)\Binaries\WPF462\Telerik.Windows.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\DefaultIcons\file32.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\DefaultIcons\photos.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\1PersonalFolders.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\2DeletedItems.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\3Drafts.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\4Inbox.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Images\search.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\beach_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\forest_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\MediaFiles\Photos\vista_small.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Readme.md" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>