
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>PdfElementsEditor</RootNamespace>
    <EnableDefaultItems>False</EnableDefaultItems>
  </PropertyGroup>
  
  <ItemGroup>
  <ApplicationDefinition Include="App.xaml">
    <Generator>MSBuild:Compile</Generator>
    <SubType>Designer</SubType>
  </ApplicationDefinition>
  <Page Include="MainWindow.xaml">
    <Generator>MSBuild:Compile</Generator>
    <SubType>Designer</SubType>
  </Page>
  <Page Include="TextEditDialog.xaml">
    <Generator>MSBuild:Compile</Generator>
  </Page>
  <Compile Include="App.xaml.cs">
    <DependentUpon>App.xaml</DependentUpon>
    <SubType>Code</SubType>
  </Compile>
  <Compile Include="CustomUILayersBuilder.cs" />
  <Compile Include="ElementModel.cs" />
  <Compile Include="HiglightElementLayer.cs" />
  <Compile Include="IconGeometries.cs" />
  <Compile Include="MainWindow.xaml.cs">
    <DependentUpon>MainWindow.xaml</DependentUpon>
    <SubType>Code</SubType>
  </Compile>
  <Compile Include="PageModel.cs" />
  <Compile Include="TextEditDialog.xaml.cs" />
</ItemGroup>
  
  <ItemGroup>
    <None Include="README.md" />
    <None Include="SamplePdf.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>

</Project>