<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>CustomHeaderTemplate</RootNamespace>
    <AssemblyName>CustomHeaderTemplate</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="ProductImages\Copy holder.png" />
    <Resource Include="ProductImages\Glare filter.png" />
    <Resource Include="ProductImages\Mouse pad.png" />
    <Resource Include="ProductImages\Printer stand.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>