<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>QueryableDataProviderPersistence</RootNamespace>
    <AssemblyName>QueryableDataProviderPersistence</AssemblyName>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EntityFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>lib\EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.Entity" />
    <Reference Include="System.Security" />
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Category.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Customer.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="CustomerDemographic.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Employee.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="NorthwindDBEntities.Context.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NorthwindDBEntities.Context.tt</DependentUpon>
    </Compile>
    <Compile Update="NorthwindDBEntities.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="NorthwindModel.Context.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NorthwindModel.Context.tt</DependentUpon>
    </Compile>
    <Compile Update="NorthwindModel.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NorthwindModel.tt</DependentUpon>
    </Compile>
    <Compile Update="Order.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Order_Detail.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Product.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Region.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Shipper.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Supplier.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
    <Compile Update="Territory.cs">
      <DependentUpon>NorthwindDBEntities.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EntityDeploy Include="NorthwindModel.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>NorthwindModel.Designer.cs</LastGenOutput>
    </EntityDeploy>
    <EntityDeploy Include="NorthwindDBEntities.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>NorthwindDBEntities.Designer.cs</LastGenOutput>
    </EntityDeploy>
    <None Update="NorthwindDBEntities.edmx.diagram">
      <DependentUpon>NorthwindDBEntities.edmx</DependentUpon>
    </None>
    <None Update="NorthwindModel.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>NorthwindModel.edmx</DependentUpon>
      <LastGenOutput>NorthwindModel.Context.cs</LastGenOutput>
    </None>
    <None Update="NorthwindModel.edmx.diagram">
      <DependentUpon>NorthwindModel.edmx</DependentUpon>
    </None>
    <None Update="NorthwindModel.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>NorthwindModel.edmx</DependentUpon>
      <LastGenOutput>NorthwindModel.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Content Include="lib\EntityFramework.dll" />
    <Resource Include="lib\EntityFramework.xml" />
    <Content Include="NorthwindDB.mdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="NorthwindDBEntities.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>NorthwindDBEntities.edmx</DependentUpon>
      <LastGenOutput>NorthwindDBEntities.Context.cs</LastGenOutput>
    </Content>
    <Content Include="NorthwindDBEntities.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>NorthwindDBEntities.edmx</DependentUpon>
      <LastGenOutput>NorthwindDBEntities.cs</LastGenOutput>
    </Content>
    <Content Include="NorthwindDB_log.ldf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>NorthwindDB.mdf</DependentUpon>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>