<?xml version="1.0" encoding="utf-8"?><Database Name="SpellCheckerDataBase" Class="SpellCheckerDataBaseDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\SpellCheckerDataBase.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SpellCheckerDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Word" Member="Words">
    <Type Name="Word">
      <Column Name="string" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>