<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build\Imports\LicensingConfig.targets" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ComputerVisionApi</RootNamespace>
    <AssemblyName>ComputerVisionApi</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ComputerVisionApi.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2">
      <Version>3.7.302</Version>
    </PackageReference>
    <Reference Include="System.Net.Http" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />
    <Reference Include="Telerik.Windows.Controls">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.DataVisualization">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.DataVisualization.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.FileDialogs">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.FileDialogs.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.GridView">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.GridView.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Input">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.Input.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Controls.Navigation">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Controls.Navigation.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Data">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Data.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Telerik.Windows.Themes.Office2016">
      <HintPath>$(TELERIKWPFDIR)\Binaries.NoXaml\WPF462\Telerik.Windows.Themes.Office2016.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>