    <Project Sdk="Microsoft.NET.Sdk"> 
		<Import Project="..\..\Build\Imports\LicensingConfig.targets" />
        <PropertyGroup> 
            <OutputType>WinExe</OutputType> 
            <TargetFramework>net8.0-windows</TargetFramework>
			<ImplicitUsings>enable</ImplicitUsings>
            <UseWPF>true</UseWPF> 
        </PropertyGroup> 
		
		<ItemGroup>
			<PackageReference Include="Telerik.Licensing" Version="$(TelerikLicensingNugetVersion)" />			
			<PackageReference Include="ZXing.Net" Version="*" />
			<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
		</ItemGroup>
		
		<ItemGroup>
			<Reference Include="Telerik.Windows.Controls">
				<SpecificVersion>False</SpecificVersion>
				<HintPath>$(TelerikBinariesNet)\Telerik.Windows.Controls.dll</HintPath>
			</Reference>
			<Reference Include="Telerik.Windows.Controls.Input">
				<SpecificVersion>False</SpecificVersion>
				<HintPath>$(TelerikBinariesNet)\Telerik.Windows.Controls.Input.dll</HintPath>
			</Reference>
		</ItemGroup>
    </Project> 