    <Project Sdk="Microsoft.NET.Sdk"> 
        <PropertyGroup> 
            <OutputType>WinExe</OutputType> 
            <TargetFramework>net10.0-windows</TargetFramework>
			<ImplicitUsings>enable</ImplicitUsings>
            <UseWPF>true</UseWPF> 
        </PropertyGroup> 
		
		<ItemGroup>
			<PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
			<PackageReference Include="ZXing.Net" Version="*" />
			<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
		</ItemGroup>
		
    </Project> 