
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("384fabe8-caf8-40d0-a129-97f466b2b0d6")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlAppointments_Categories", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Category), "SqlAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlAppointment), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_Categories", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Category), "SqlExceptionAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlExceptionAppointment), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlAppointment), "SqlAppointmentResources", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlAppointmentResource), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlResource", "SqlResources", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlResource), "SqlAppointmentResources", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlAppointmentResource), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlAppointments_TimeMarkers", "TimeMarkers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(TimeMarker), "SqlAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlAppointment), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlAppointment), "SqlExceptionOccurrences", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlExceptionOccurrence), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlExceptionOccurrence), "SqlExceptionAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(SqlExceptionAppointment), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(TimeMarker), "SqlExceptionAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlExceptionAppointment), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlExceptionAppointment), "SqlExceptionResources", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlExceptionResource), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlResource", "SqlResources", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(SqlResource), "SqlExceptionResources", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlExceptionResource), True)>
<Assembly: EdmRelationshipAttribute("ScheduleViewDBModel", "FK_SqlResources_SqlResourceTypes", "SqlResourceTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(SqlResourceType), "SqlResources", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SqlResource), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class ScheduleViewDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new ScheduleViewDBEntities object using the connection string found in the 'ScheduleViewDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=ScheduleViewDBEntities", "ScheduleViewDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ScheduleViewDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "ScheduleViewDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new ScheduleViewDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "ScheduleViewDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Categories() As ObjectSet(Of Category)
        Get
            If (_Categories Is Nothing) Then
                _Categories = MyBase.CreateObjectSet(Of Category)("Categories")
            End If
            Return _Categories
        End Get
    End Property

    Private _Categories As ObjectSet(Of Category)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlAppointmentResources() As ObjectSet(Of SqlAppointmentResource)
        Get
            If (_SqlAppointmentResources Is Nothing) Then
                _SqlAppointmentResources = MyBase.CreateObjectSet(Of SqlAppointmentResource)("SqlAppointmentResources")
            End If
            Return _SqlAppointmentResources
        End Get
    End Property

    Private _SqlAppointmentResources As ObjectSet(Of SqlAppointmentResource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlAppointments() As ObjectSet(Of SqlAppointment)
        Get
            If (_SqlAppointments Is Nothing) Then
                _SqlAppointments = MyBase.CreateObjectSet(Of SqlAppointment)("SqlAppointments")
            End If
            Return _SqlAppointments
        End Get
    End Property

    Private _SqlAppointments As ObjectSet(Of SqlAppointment)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlExceptionAppointments() As ObjectSet(Of SqlExceptionAppointment)
        Get
            If (_SqlExceptionAppointments Is Nothing) Then
                _SqlExceptionAppointments = MyBase.CreateObjectSet(Of SqlExceptionAppointment)("SqlExceptionAppointments")
            End If
            Return _SqlExceptionAppointments
        End Get
    End Property

    Private _SqlExceptionAppointments As ObjectSet(Of SqlExceptionAppointment)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlExceptionOccurrences() As ObjectSet(Of SqlExceptionOccurrence)
        Get
            If (_SqlExceptionOccurrences Is Nothing) Then
                _SqlExceptionOccurrences = MyBase.CreateObjectSet(Of SqlExceptionOccurrence)("SqlExceptionOccurrences")
            End If
            Return _SqlExceptionOccurrences
        End Get
    End Property

    Private _SqlExceptionOccurrences As ObjectSet(Of SqlExceptionOccurrence)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlExceptionResources() As ObjectSet(Of SqlExceptionResource)
        Get
            If (_SqlExceptionResources Is Nothing) Then
                _SqlExceptionResources = MyBase.CreateObjectSet(Of SqlExceptionResource)("SqlExceptionResources")
            End If
            Return _SqlExceptionResources
        End Get
    End Property

    Private _SqlExceptionResources As ObjectSet(Of SqlExceptionResource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlResources() As ObjectSet(Of SqlResource)
        Get
            If (_SqlResources Is Nothing) Then
                _SqlResources = MyBase.CreateObjectSet(Of SqlResource)("SqlResources")
            End If
            Return _SqlResources
        End Get
    End Property

    Private _SqlResources As ObjectSet(Of SqlResource)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SqlResourceTypes() As ObjectSet(Of SqlResourceType)
        Get
            If (_SqlResourceTypes Is Nothing) Then
                _SqlResourceTypes = MyBase.CreateObjectSet(Of SqlResourceType)("SqlResourceTypes")
            End If
            Return _SqlResourceTypes
        End Get
    End Property

    Private _SqlResourceTypes As ObjectSet(Of SqlResourceType)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TimeMarkers() As ObjectSet(Of TimeMarker)
        Get
            If (_TimeMarkers Is Nothing) Then
                _TimeMarkers = MyBase.CreateObjectSet(Of TimeMarker)("TimeMarkers")
            End If
            Return _TimeMarkers
        End Get
    End Property

    Private _TimeMarkers As ObjectSet(Of TimeMarker)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCategories(ByVal category As Category)
        MyBase.AddObject("Categories", category)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlAppointmentResources EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlAppointmentResources(ByVal sqlAppointmentResource As SqlAppointmentResource)
        MyBase.AddObject("SqlAppointmentResources", sqlAppointmentResource)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlAppointments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlAppointments(ByVal sqlAppointment As SqlAppointment)
        MyBase.AddObject("SqlAppointments", sqlAppointment)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlExceptionAppointments EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlExceptionAppointments(ByVal sqlExceptionAppointment As SqlExceptionAppointment)
        MyBase.AddObject("SqlExceptionAppointments", sqlExceptionAppointment)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlExceptionOccurrences EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlExceptionOccurrences(ByVal sqlExceptionOccurrence As SqlExceptionOccurrence)
        MyBase.AddObject("SqlExceptionOccurrences", sqlExceptionOccurrence)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlExceptionResources EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlExceptionResources(ByVal sqlExceptionResource As SqlExceptionResource)
        MyBase.AddObject("SqlExceptionResources", sqlExceptionResource)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlResources EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlResources(ByVal sqlResource As SqlResource)
        MyBase.AddObject("SqlResources", sqlResource)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SqlResourceTypes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSqlResourceTypes(ByVal sqlResourceType As SqlResourceType)
        MyBase.AddObject("SqlResourceTypes", sqlResourceType)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TimeMarkers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTimeMarkers(ByVal timeMarker As TimeMarker)
        MyBase.AddObject("TimeMarkers", timeMarker)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="Category")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Category
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Category object.
    ''' </summary>
    ''' <param name="categoryID">Initial value of the CategoryID property.</param>
    Public Shared Function CreateCategory(categoryID As Global.System.Int32) As Category
        Dim category as Category = New Category
        category.CategoryID = categoryID
        Return category
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CategoryID() As Global.System.Int32
        Get
            Return _CategoryID
        End Get
        Set
            If (_CategoryID <> Value) Then
                OnCategoryIDChanging(value)
                ReportPropertyChanging("CategoryID")
                _CategoryID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CategoryID")
                OnCategoryIDChanged()
            End If
        End Set
    End Property

    Private _CategoryID As Global.System.Int32
    Private Partial Sub OnCategoryIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnCategoryIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryName() As Global.System.String
        Get
            Return _CategoryName
        End Get
        Set
            OnCategoryNameChanging(value)
            ReportPropertyChanging("CategoryName")
            _CategoryName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CategoryName")
            OnCategoryNameChanged()
        End Set
    End Property

    Private _CategoryName As Global.System.String
    Private Partial Sub OnCategoryNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DisplayName() As Global.System.String
        Get
            Return _DisplayName
        End Get
        Set
            OnDisplayNameChanging(value)
            ReportPropertyChanging("DisplayName")
            _DisplayName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DisplayName")
            OnDisplayNameChanged()
        End Set
    End Property

    Private _DisplayName As Global.System.String
    Private Partial Sub OnDisplayNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDisplayNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryBrushName() As Global.System.String
        Get
            Return _CategoryBrushName
        End Get
        Set
            OnCategoryBrushNameChanging(value)
            ReportPropertyChanging("CategoryBrushName")
            _CategoryBrushName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CategoryBrushName")
            OnCategoryBrushNameChanged()
        End Set
    End Property

    Private _CategoryBrushName As Global.System.String
    Private Partial Sub OnCategoryBrushNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCategoryBrushNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointments_Categories", "SqlAppointments")>
     Public Property SqlAppointments() As EntityCollection(Of SqlAppointment)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "SqlAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "SqlAppointments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_Categories", "SqlExceptionAppointments")>
     Public Property SqlExceptionAppointments() As EntityCollection(Of SqlExceptionAppointment)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "SqlExceptionAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "SqlExceptionAppointments", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlAppointment")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlAppointment
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlAppointment object.
    ''' </summary>
    ''' <param name="sqlAppointmentId">Initial value of the SqlAppointmentId property.</param>
    ''' <param name="start">Initial value of the Start property.</param>
    ''' <param name="end">Initial value of the End property.</param>
    ''' <param name="isAllDayEvent">Initial value of the IsAllDayEvent property.</param>
    ''' <param name="importance">Initial value of the Importance property.</param>
    Public Shared Function CreateSqlAppointment(sqlAppointmentId As Global.System.Int32, start As Global.System.DateTime, [end] As Global.System.DateTime, isAllDayEvent As Global.System.Boolean, importance As Global.System.Int32) As SqlAppointment
        Dim sqlAppointment as SqlAppointment = New SqlAppointment
        sqlAppointment.SqlAppointmentId = sqlAppointmentId
        sqlAppointment.Start = start
        sqlAppointment.[End] = [end]
        sqlAppointment.IsAllDayEvent = isAllDayEvent
        sqlAppointment.Importance = importance
        Return sqlAppointment
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlAppointmentId() As Global.System.Int32
        Get
            Return _SqlAppointmentId
        End Get
        Set
            If (_SqlAppointmentId <> Value) Then
                OnSqlAppointmentIdChanging(value)
                ReportPropertyChanging("SqlAppointmentId")
                _SqlAppointmentId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlAppointmentId")
                OnSqlAppointmentIdChanged()
            End If
        End Set
    End Property

    Private _SqlAppointmentId As Global.System.Int32
    Private Partial Sub OnSqlAppointmentIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlAppointmentIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Subject() As Global.System.String
        Get
            Return _Subject
        End Get
        Set
            OnSubjectChanging(value)
            ReportPropertyChanging("Subject")
            _Subject = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Subject")
            OnSubjectChanged()
        End Set
    End Property

    Private _Subject As Global.System.String
    Private Partial Sub OnSubjectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSubjectChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Body() As Global.System.String
        Get
            Return _Body
        End Get
        Set
            OnBodyChanging(value)
            ReportPropertyChanging("Body")
            _Body = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Body")
            OnBodyChanged()
        End Set
    End Property

    Private _Body As Global.System.String
    Private Partial Sub OnBodyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBodyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Start() As Global.System.DateTime
        Get
            Return _Start
        End Get
        Set
            OnStartChanging(value)
            ReportPropertyChanging("Start")
            _Start = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Start")
            OnStartChanged()
        End Set
    End Property

    Private _Start As Global.System.DateTime
    Private Partial Sub OnStartChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnStartChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [End]() As Global.System.DateTime
        Get
            Return _End
        End Get
        Set
            OnEndChanging(value)
            ReportPropertyChanging("End")
            _End = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("End")
            OnEndChanged()
        End Set
    End Property

    Private _End As Global.System.DateTime
    Private Partial Sub OnEndChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnEndChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsAllDayEvent() As Global.System.Boolean
        Get
            Return _IsAllDayEvent
        End Get
        Set
            OnIsAllDayEventChanging(value)
            ReportPropertyChanging("IsAllDayEvent")
            _IsAllDayEvent = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IsAllDayEvent")
            OnIsAllDayEventChanged()
        End Set
    End Property

    Private _IsAllDayEvent As Global.System.Boolean
    Private Partial Sub OnIsAllDayEventChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnIsAllDayEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RecurrencePattern() As Global.System.String
        Get
            Return _RecurrencePattern
        End Get
        Set
            OnRecurrencePatternChanging(value)
            ReportPropertyChanging("RecurrencePattern")
            _RecurrencePattern = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RecurrencePattern")
            OnRecurrencePatternChanged()
        End Set
    End Property

    Private _RecurrencePattern As Global.System.String
    Private Partial Sub OnRecurrencePatternChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRecurrencePatternChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeZoneString() As Global.System.String
        Get
            Return _TimeZoneString
        End Get
        Set
            OnTimeZoneStringChanging(value)
            ReportPropertyChanging("TimeZoneString")
            _TimeZoneString = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TimeZoneString")
            OnTimeZoneStringChanged()
        End Set
    End Property

    Private _TimeZoneString As Global.System.String
    Private Partial Sub OnTimeZoneStringChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTimeZoneStringChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Importance() As Global.System.Int32
        Get
            Return _Importance
        End Get
        Set
            OnImportanceChanging(value)
            ReportPropertyChanging("Importance")
            _Importance = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Importance")
            OnImportanceChanged()
        End Set
    End Property

    Private _Importance As Global.System.Int32
    Private Partial Sub OnImportanceChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnImportanceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeMarkerID() As Nullable(Of Global.System.Int32)
        Get
            Return _TimeMarkerID
        End Get
        Set
            OnTimeMarkerIDChanging(value)
            ReportPropertyChanging("TimeMarkerID")
            _TimeMarkerID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TimeMarkerID")
            OnTimeMarkerIDChanged()
        End Set
    End Property

    Private _TimeMarkerID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTimeMarkerIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTimeMarkerIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryID() As Nullable(Of Global.System.Int32)
        Get
            Return _CategoryID
        End Get
        Set
            OnCategoryIDChanging(value)
            ReportPropertyChanging("CategoryID")
            _CategoryID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CategoryID")
            OnCategoryIDChanged()
        End Set
    End Property

    Private _CategoryID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCategoryIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCategoryIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointments_Categories", "Categories")>
    Public Property Category() As Category
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "Categories").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "Categories").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CategoryReference() As EntityReference(Of Category)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "Categories")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlAppointments_Categories", "Categories", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlAppointment", "SqlAppointmentResources")>
     Public Property SqlAppointmentResources() As EntityCollection(Of SqlAppointmentResource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlAppointmentResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointmentResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlAppointmentResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointmentResources", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointments_TimeMarkers", "TimeMarkers")>
    Public Property TimeMarker() As TimeMarker
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "TimeMarkers").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "TimeMarkers").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TimeMarkerReference() As EntityReference(Of TimeMarker)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "TimeMarkers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "TimeMarkers", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionOccurrences_SqlAppointments", "SqlExceptionOccurrences")>
     Public Property SqlExceptionOccurrences() As EntityCollection(Of SqlExceptionOccurrence)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlExceptionOccurrences")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlExceptionOccurrences", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlAppointmentResource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlAppointmentResource
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlAppointmentResource object.
    ''' </summary>
    ''' <param name="sqlAppointments_SqlAppointmentId">Initial value of the SqlAppointments_SqlAppointmentId property.</param>
    ''' <param name="sqlResources_SqlResourceId">Initial value of the SqlResources_SqlResourceId property.</param>
    Public Shared Function CreateSqlAppointmentResource(sqlAppointments_SqlAppointmentId As Global.System.Int32, sqlResources_SqlResourceId As Global.System.Int32) As SqlAppointmentResource
        Dim sqlAppointmentResource as SqlAppointmentResource = New SqlAppointmentResource
        sqlAppointmentResource.SqlAppointments_SqlAppointmentId = sqlAppointments_SqlAppointmentId
        sqlAppointmentResource.SqlResources_SqlResourceId = sqlResources_SqlResourceId
        Return sqlAppointmentResource
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlAppointments_SqlAppointmentId() As Global.System.Int32
        Get
            Return _SqlAppointments_SqlAppointmentId
        End Get
        Set
            If (_SqlAppointments_SqlAppointmentId <> Value) Then
                OnSqlAppointments_SqlAppointmentIdChanging(value)
                ReportPropertyChanging("SqlAppointments_SqlAppointmentId")
                _SqlAppointments_SqlAppointmentId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlAppointments_SqlAppointmentId")
                OnSqlAppointments_SqlAppointmentIdChanged()
            End If
        End Set
    End Property

    Private _SqlAppointments_SqlAppointmentId As Global.System.Int32
    Private Partial Sub OnSqlAppointments_SqlAppointmentIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlAppointments_SqlAppointmentIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlResources_SqlResourceId() As Global.System.Int32
        Get
            Return _SqlResources_SqlResourceId
        End Get
        Set
            If (_SqlResources_SqlResourceId <> Value) Then
                OnSqlResources_SqlResourceIdChanging(value)
                ReportPropertyChanging("SqlResources_SqlResourceId")
                _SqlResources_SqlResourceId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlResources_SqlResourceId")
                OnSqlResources_SqlResourceIdChanged()
            End If
        End Set
    End Property

    Private _SqlResources_SqlResourceId As Global.System.Int32
    Private Partial Sub OnSqlResources_SqlResourceIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlResources_SqlResourceIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ManyToManyWorkaround() As Nullable(Of Global.System.Boolean)
        Get
            Return _ManyToManyWorkaround
        End Get
        Set
            OnManyToManyWorkaroundChanging(value)
            ReportPropertyChanging("ManyToManyWorkaround")
            _ManyToManyWorkaround = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ManyToManyWorkaround")
            OnManyToManyWorkaroundChanged()
        End Set
    End Property

    Private _ManyToManyWorkaround As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnManyToManyWorkaroundChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnManyToManyWorkaroundChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments")>
    Public Property SqlAppointment() As SqlAppointment
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlAppointmentReference() As EntityReference(Of SqlAppointment)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlAppointment", "SqlAppointments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlResource", "SqlResources")>
    Public Property SqlResource() As SqlResource
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlResources").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlResources").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlResourceReference() As EntityReference(Of SqlResource)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlResources", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlExceptionAppointment")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlExceptionAppointment
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlExceptionAppointment object.
    ''' </summary>
    ''' <param name="exceptionId">Initial value of the ExceptionId property.</param>
    ''' <param name="start">Initial value of the Start property.</param>
    ''' <param name="end">Initial value of the End property.</param>
    ''' <param name="isAllDayEvent">Initial value of the IsAllDayEvent property.</param>
    ''' <param name="importance">Initial value of the Importance property.</param>
    Public Shared Function CreateSqlExceptionAppointment(exceptionId As Global.System.Int32, start As Global.System.DateTime, [end] As Global.System.DateTime, isAllDayEvent As Global.System.Boolean, importance As Global.System.Int32) As SqlExceptionAppointment
        Dim sqlExceptionAppointment as SqlExceptionAppointment = New SqlExceptionAppointment
        sqlExceptionAppointment.ExceptionId = exceptionId
        sqlExceptionAppointment.Start = start
        sqlExceptionAppointment.[End] = [end]
        sqlExceptionAppointment.IsAllDayEvent = isAllDayEvent
        sqlExceptionAppointment.Importance = importance
        Return sqlExceptionAppointment
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ExceptionId() As Global.System.Int32
        Get
            Return _ExceptionId
        End Get
        Set
            If (_ExceptionId <> Value) Then
                OnExceptionIdChanging(value)
                ReportPropertyChanging("ExceptionId")
                _ExceptionId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ExceptionId")
                OnExceptionIdChanged()
            End If
        End Set
    End Property

    Private _ExceptionId As Global.System.Int32
    Private Partial Sub OnExceptionIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnExceptionIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Subject() As Global.System.String
        Get
            Return _Subject
        End Get
        Set
            OnSubjectChanging(value)
            ReportPropertyChanging("Subject")
            _Subject = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Subject")
            OnSubjectChanged()
        End Set
    End Property

    Private _Subject As Global.System.String
    Private Partial Sub OnSubjectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSubjectChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Body() As Global.System.String
        Get
            Return _Body
        End Get
        Set
            OnBodyChanging(value)
            ReportPropertyChanging("Body")
            _Body = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Body")
            OnBodyChanged()
        End Set
    End Property

    Private _Body As Global.System.String
    Private Partial Sub OnBodyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBodyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Start() As Global.System.DateTime
        Get
            Return _Start
        End Get
        Set
            OnStartChanging(value)
            ReportPropertyChanging("Start")
            _Start = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Start")
            OnStartChanged()
        End Set
    End Property

    Private _Start As Global.System.DateTime
    Private Partial Sub OnStartChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnStartChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [End]() As Global.System.DateTime
        Get
            Return _End
        End Get
        Set
            OnEndChanging(value)
            ReportPropertyChanging("End")
            _End = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("End")
            OnEndChanged()
        End Set
    End Property

    Private _End As Global.System.DateTime
    Private Partial Sub OnEndChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnEndChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IsAllDayEvent() As Global.System.Boolean
        Get
            Return _IsAllDayEvent
        End Get
        Set
            OnIsAllDayEventChanging(value)
            ReportPropertyChanging("IsAllDayEvent")
            _IsAllDayEvent = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IsAllDayEvent")
            OnIsAllDayEventChanged()
        End Set
    End Property

    Private _IsAllDayEvent As Global.System.Boolean
    Private Partial Sub OnIsAllDayEventChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnIsAllDayEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeZoneString() As Global.System.String
        Get
            Return _TimeZoneString
        End Get
        Set
            OnTimeZoneStringChanging(value)
            ReportPropertyChanging("TimeZoneString")
            _TimeZoneString = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TimeZoneString")
            OnTimeZoneStringChanged()
        End Set
    End Property

    Private _TimeZoneString As Global.System.String
    Private Partial Sub OnTimeZoneStringChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTimeZoneStringChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Importance() As Global.System.Int32
        Get
            Return _Importance
        End Get
        Set
            OnImportanceChanging(value)
            ReportPropertyChanging("Importance")
            _Importance = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Importance")
            OnImportanceChanged()
        End Set
    End Property

    Private _Importance As Global.System.Int32
    Private Partial Sub OnImportanceChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnImportanceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeMarkerID() As Nullable(Of Global.System.Int32)
        Get
            Return _TimeMarkerID
        End Get
        Set
            OnTimeMarkerIDChanging(value)
            ReportPropertyChanging("TimeMarkerID")
            _TimeMarkerID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TimeMarkerID")
            OnTimeMarkerIDChanged()
        End Set
    End Property

    Private _TimeMarkerID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnTimeMarkerIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnTimeMarkerIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CategoryID() As Nullable(Of Global.System.Int32)
        Get
            Return _CategoryID
        End Get
        Set
            OnCategoryIDChanging(value)
            ReportPropertyChanging("CategoryID")
            _CategoryID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CategoryID")
            OnCategoryIDChanged()
        End Set
    End Property

    Private _CategoryID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCategoryIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCategoryIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_Categories", "Categories")>
    Public Property Category() As Category
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "Categories").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "Categories").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CategoryReference() As EntityReference(Of Category)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "Categories")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Category)("ScheduleViewDBModel.FK_SqlExceptionAppointments_Categories", "Categories", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences")>
    Public Property SqlExceptionOccurrence() As SqlExceptionOccurrence
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlExceptionOccurrenceReference() As EntityReference(Of SqlExceptionOccurrence)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlExceptionOccurrence)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionOccurrences", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers")>
    Public Property TimeMarker() As TimeMarker
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TimeMarkerReference() As EntityReference(Of TimeMarker)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of TimeMarker)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "TimeMarkers", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionResources")>
     Public Property SqlExceptionResources() As EntityCollection(Of SqlExceptionResource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlExceptionResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlExceptionResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionResources", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlExceptionOccurrence")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlExceptionOccurrence
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlExceptionOccurrence object.
    ''' </summary>
    ''' <param name="exceptionId">Initial value of the ExceptionId property.</param>
    ''' <param name="masterSqlAppointmentId">Initial value of the MasterSqlAppointmentId property.</param>
    ''' <param name="exceptionDate">Initial value of the ExceptionDate property.</param>
    Public Shared Function CreateSqlExceptionOccurrence(exceptionId As Global.System.Int32, masterSqlAppointmentId As Global.System.Int32, exceptionDate As Global.System.DateTime) As SqlExceptionOccurrence
        Dim sqlExceptionOccurrence as SqlExceptionOccurrence = New SqlExceptionOccurrence
        sqlExceptionOccurrence.ExceptionId = exceptionId
        sqlExceptionOccurrence.MasterSqlAppointmentId = masterSqlAppointmentId
        sqlExceptionOccurrence.ExceptionDate = exceptionDate
        Return sqlExceptionOccurrence
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ExceptionId() As Global.System.Int32
        Get
            Return _ExceptionId
        End Get
        Set
            If (_ExceptionId <> Value) Then
                OnExceptionIdChanging(value)
                ReportPropertyChanging("ExceptionId")
                _ExceptionId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ExceptionId")
                OnExceptionIdChanged()
            End If
        End Set
    End Property

    Private _ExceptionId As Global.System.Int32
    Private Partial Sub OnExceptionIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnExceptionIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MasterSqlAppointmentId() As Global.System.Int32
        Get
            Return _MasterSqlAppointmentId
        End Get
        Set
            OnMasterSqlAppointmentIdChanging(value)
            ReportPropertyChanging("MasterSqlAppointmentId")
            _MasterSqlAppointmentId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MasterSqlAppointmentId")
            OnMasterSqlAppointmentIdChanged()
        End Set
    End Property

    Private _MasterSqlAppointmentId As Global.System.Int32
    Private Partial Sub OnMasterSqlAppointmentIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMasterSqlAppointmentIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ExceptionDate() As Global.System.DateTime
        Get
            Return _ExceptionDate
        End Get
        Set
            OnExceptionDateChanging(value)
            ReportPropertyChanging("ExceptionDate")
            _ExceptionDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ExceptionDate")
            OnExceptionDateChanged()
        End Set
    End Property

    Private _ExceptionDate As Global.System.DateTime
    Private Partial Sub OnExceptionDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnExceptionDateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments")>
    Public Property SqlAppointment() As SqlAppointment
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlAppointmentReference() As EntityReference(Of SqlAppointment)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlExceptionOccurrences_SqlAppointments", "SqlAppointments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionAppointments")>
    Public Property SqlExceptionAppointment() As SqlExceptionAppointment
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionAppointments").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionAppointments").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlExceptionAppointmentReference() As EntityReference(Of SqlExceptionAppointment)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_SqlExceptionOccurrences", "SqlExceptionAppointments", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlExceptionResource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlExceptionResource
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlExceptionResource object.
    ''' </summary>
    ''' <param name="sqlExceptionAppointments_ExceptionId">Initial value of the SqlExceptionAppointments_ExceptionId property.</param>
    ''' <param name="sqlResources_SqlResourceId">Initial value of the SqlResources_SqlResourceId property.</param>
    Public Shared Function CreateSqlExceptionResource(sqlExceptionAppointments_ExceptionId As Global.System.Int32, sqlResources_SqlResourceId As Global.System.Int32) As SqlExceptionResource
        Dim sqlExceptionResource as SqlExceptionResource = New SqlExceptionResource
        sqlExceptionResource.SqlExceptionAppointments_ExceptionId = sqlExceptionAppointments_ExceptionId
        sqlExceptionResource.SqlResources_SqlResourceId = sqlResources_SqlResourceId
        Return sqlExceptionResource
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlExceptionAppointments_ExceptionId() As Global.System.Int32
        Get
            Return _SqlExceptionAppointments_ExceptionId
        End Get
        Set
            If (_SqlExceptionAppointments_ExceptionId <> Value) Then
                OnSqlExceptionAppointments_ExceptionIdChanging(value)
                ReportPropertyChanging("SqlExceptionAppointments_ExceptionId")
                _SqlExceptionAppointments_ExceptionId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlExceptionAppointments_ExceptionId")
                OnSqlExceptionAppointments_ExceptionIdChanged()
            End If
        End Set
    End Property

    Private _SqlExceptionAppointments_ExceptionId As Global.System.Int32
    Private Partial Sub OnSqlExceptionAppointments_ExceptionIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlExceptionAppointments_ExceptionIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlResources_SqlResourceId() As Global.System.Int32
        Get
            Return _SqlResources_SqlResourceId
        End Get
        Set
            If (_SqlResources_SqlResourceId <> Value) Then
                OnSqlResources_SqlResourceIdChanging(value)
                ReportPropertyChanging("SqlResources_SqlResourceId")
                _SqlResources_SqlResourceId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlResources_SqlResourceId")
                OnSqlResources_SqlResourceIdChanged()
            End If
        End Set
    End Property

    Private _SqlResources_SqlResourceId As Global.System.Int32
    Private Partial Sub OnSqlResources_SqlResourceIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlResources_SqlResourceIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ManyToManyWorkaround() As Nullable(Of Global.System.Boolean)
        Get
            Return _ManyToManyWorkaround
        End Get
        Set
            OnManyToManyWorkaroundChanging(value)
            ReportPropertyChanging("ManyToManyWorkaround")
            _ManyToManyWorkaround = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ManyToManyWorkaround")
            OnManyToManyWorkaroundChanged()
        End Set
    End Property

    Private _ManyToManyWorkaround As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnManyToManyWorkaroundChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnManyToManyWorkaroundChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments")>
    Public Property SqlExceptionAppointment() As SqlExceptionAppointment
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlExceptionAppointmentReference() As EntityReference(Of SqlExceptionAppointment)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlExceptionAppointment", "SqlExceptionAppointments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlResource", "SqlResources")>
    Public Property SqlResource() As SqlResource
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlResources").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlResources").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlResourceReference() As EntityReference(Of SqlResource)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlResources", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlResource")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlResource
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlResource object.
    ''' </summary>
    ''' <param name="sqlResourceId">Initial value of the SqlResourceId property.</param>
    Public Shared Function CreateSqlResource(sqlResourceId As Global.System.Int32) As SqlResource
        Dim sqlResource as SqlResource = New SqlResource
        sqlResource.SqlResourceId = sqlResourceId
        Return sqlResource
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlResourceId() As Global.System.Int32
        Get
            Return _SqlResourceId
        End Get
        Set
            If (_SqlResourceId <> Value) Then
                OnSqlResourceIdChanging(value)
                ReportPropertyChanging("SqlResourceId")
                _SqlResourceId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlResourceId")
                OnSqlResourceIdChanged()
            End If
        End Set
    End Property

    Private _SqlResourceId As Global.System.Int32
    Private Partial Sub OnSqlResourceIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlResourceIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SqlResourceTypeId() As Nullable(Of Global.System.Int32)
        Get
            Return _SqlResourceTypeId
        End Get
        Set
            OnSqlResourceTypeIdChanging(value)
            ReportPropertyChanging("SqlResourceTypeId")
            _SqlResourceTypeId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SqlResourceTypeId")
            OnSqlResourceTypeIdChanged()
        End Set
    End Property

    Private _SqlResourceTypeId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnSqlResourceTypeIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnSqlResourceTypeIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ResourceName() As Global.System.String
        Get
            Return _ResourceName
        End Get
        Set
            OnResourceNameChanging(value)
            ReportPropertyChanging("ResourceName")
            _ResourceName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ResourceName")
            OnResourceNameChanged()
        End Set
    End Property

    Private _ResourceName As Global.System.String
    Private Partial Sub OnResourceNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnResourceNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DisplayName() As Global.System.String
        Get
            Return _DisplayName
        End Get
        Set
            OnDisplayNameChanging(value)
            ReportPropertyChanging("DisplayName")
            _DisplayName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DisplayName")
            OnDisplayNameChanged()
        End Set
    End Property

    Private _DisplayName As Global.System.String
    Private Partial Sub OnDisplayNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDisplayNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointmentResources_SqlResource", "SqlAppointmentResources")>
     Public Property SqlAppointmentResources() As EntityCollection(Of SqlAppointmentResource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlAppointmentResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlAppointmentResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlAppointmentResource)("ScheduleViewDBModel.FK_SqlAppointmentResources_SqlResource", "SqlAppointmentResources", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionResources_SqlResource", "SqlExceptionResources")>
     Public Property SqlExceptionResources() As EntityCollection(Of SqlExceptionResource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlExceptionResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlExceptionResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlExceptionResource)("ScheduleViewDBModel.FK_SqlExceptionResources_SqlResource", "SqlExceptionResources", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlResources_SqlResourceTypes", "SqlResourceTypes")>
    Public Property SqlResourceType() As SqlResourceType
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResourceType)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResourceTypes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResourceType)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResourceTypes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SqlResourceTypeReference() As EntityReference(Of SqlResourceType)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SqlResourceType)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResourceTypes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SqlResourceType)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResourceTypes", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="SqlResourceType")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SqlResourceType
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SqlResourceType object.
    ''' </summary>
    ''' <param name="sqlResourceTypeId">Initial value of the SqlResourceTypeId property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="allowMultipleSelection">Initial value of the AllowMultipleSelection property.</param>
    Public Shared Function CreateSqlResourceType(sqlResourceTypeId As Global.System.Int32, name As Global.System.String, allowMultipleSelection As Global.System.Boolean) As SqlResourceType
        Dim sqlResourceType as SqlResourceType = New SqlResourceType
        sqlResourceType.SqlResourceTypeId = sqlResourceTypeId
        sqlResourceType.Name = name
        sqlResourceType.AllowMultipleSelection = allowMultipleSelection
        Return sqlResourceType
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SqlResourceTypeId() As Global.System.Int32
        Get
            Return _SqlResourceTypeId
        End Get
        Set
            If (_SqlResourceTypeId <> Value) Then
                OnSqlResourceTypeIdChanging(value)
                ReportPropertyChanging("SqlResourceTypeId")
                _SqlResourceTypeId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SqlResourceTypeId")
                OnSqlResourceTypeIdChanged()
            End If
        End Set
    End Property

    Private _SqlResourceTypeId As Global.System.Int32
    Private Partial Sub OnSqlResourceTypeIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnSqlResourceTypeIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DisplayName() As Global.System.String
        Get
            Return _DisplayName
        End Get
        Set
            OnDisplayNameChanging(value)
            ReportPropertyChanging("DisplayName")
            _DisplayName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DisplayName")
            OnDisplayNameChanged()
        End Set
    End Property

    Private _DisplayName As Global.System.String
    Private Partial Sub OnDisplayNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDisplayNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AllowMultipleSelection() As Global.System.Boolean
        Get
            Return _AllowMultipleSelection
        End Get
        Set
            OnAllowMultipleSelectionChanging(value)
            ReportPropertyChanging("AllowMultipleSelection")
            _AllowMultipleSelection = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AllowMultipleSelection")
            OnAllowMultipleSelectionChanged()
        End Set
    End Property

    Private _AllowMultipleSelection As Global.System.Boolean
    Private Partial Sub OnAllowMultipleSelectionChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAllowMultipleSelectionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlResources_SqlResourceTypes", "SqlResources")>
     Public Property SqlResources() As EntityCollection(Of SqlResource)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlResource)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResources")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlResource)("ScheduleViewDBModel.FK_SqlResources_SqlResourceTypes", "SqlResources", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ScheduleViewDBModel", Name:="TimeMarker")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TimeMarker
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TimeMarker object.
    ''' </summary>
    ''' <param name="timeMarkersId">Initial value of the TimeMarkersId property.</param>
    Public Shared Function CreateTimeMarker(timeMarkersId As Global.System.Int32) As TimeMarker
        Dim timeMarker as TimeMarker = New TimeMarker
        timeMarker.TimeMarkersId = timeMarkersId
        Return timeMarker
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TimeMarkersId() As Global.System.Int32
        Get
            Return _TimeMarkersId
        End Get
        Set
            If (_TimeMarkersId <> Value) Then
                OnTimeMarkersIdChanging(value)
                ReportPropertyChanging("TimeMarkersId")
                _TimeMarkersId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("TimeMarkersId")
                OnTimeMarkersIdChanged()
            End If
        End Set
    End Property

    Private _TimeMarkersId As Global.System.Int32
    Private Partial Sub OnTimeMarkersIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnTimeMarkersIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeMarkerName() As Global.System.String
        Get
            Return _TimeMarkerName
        End Get
        Set
            OnTimeMarkerNameChanging(value)
            ReportPropertyChanging("TimeMarkerName")
            _TimeMarkerName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TimeMarkerName")
            OnTimeMarkerNameChanged()
        End Set
    End Property

    Private _TimeMarkerName As Global.System.String
    Private Partial Sub OnTimeMarkerNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTimeMarkerNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TimeMarkerBrushName() As Global.System.String
        Get
            Return _TimeMarkerBrushName
        End Get
        Set
            OnTimeMarkerBrushNameChanging(value)
            ReportPropertyChanging("TimeMarkerBrushName")
            _TimeMarkerBrushName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("TimeMarkerBrushName")
            OnTimeMarkerBrushNameChanged()
        End Set
    End Property

    Private _TimeMarkerBrushName As Global.System.String
    Private Partial Sub OnTimeMarkerBrushNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTimeMarkerBrushNameChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlAppointments_TimeMarkers", "SqlAppointments")>
     Public Property SqlAppointments() As EntityCollection(Of SqlAppointment)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "SqlAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlAppointment)("ScheduleViewDBModel.FK_SqlAppointments_TimeMarkers", "SqlAppointments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ScheduleViewDBModel", "FK_SqlExceptionAppointments_TimeMarkers", "SqlExceptionAppointments")>
     Public Property SqlExceptionAppointments() As EntityCollection(Of SqlExceptionAppointment)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "SqlExceptionAppointments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SqlExceptionAppointment)("ScheduleViewDBModel.FK_SqlExceptionAppointments_TimeMarkers", "SqlExceptionAppointments", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


