<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>RadWizardDynamicLocalization</RootNamespace>
    <AssemblyName>RadWizardDynamicLocalization</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Libs\de\Telerik.Windows.Controls.resources.dll" />
    <Content Include="Libs\es\Telerik.Windows.Controls.resources.dll" />
    <Content Include="Libs\fr\Telerik.Windows.Controls.resources.dll" />
    <Content Include="Libs\it\Telerik.Windows.Controls.resources.dll" />
    <Content Include="Libs\nl\Telerik.Windows.Controls.resources.dll" />
    <Content Include="Libs\tr\Telerik.Windows.Controls.resources.dll" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>