<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SpeechToTextApi</RootNamespace>
    <AssemblyName>SpeechToTextApi</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>SpeechToTextApi.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2">
      <Version>3.7.302</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.ProjectOxford.SpeechRecognition-x86">
      <Version>1.0.0.7</Version>
    </PackageReference>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>