<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Computer.png" />
    <Resource Include="Images\Drive.png" />
    <Resource Include="Images\File.png" />
    <Resource Include="Images\Folder.png" />
    <Resource Include="Images\MoveAllItems.png" />
    <Resource Include="Images\MoveItems.png" />
    <Resource Include="Images\RemoveAllItems.png" />
    <Resource Include="Images\RemoveItems.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>