//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PdfViewerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfViewerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.PdfViewerResources", typeof(PdfViewerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string BusyIndicatorLoading {
            get {
                return ResourceManager.GetString("BusyIndicatorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the beginning of the document..
        /// </summary>
        public static string FixedDocumentViewers_BeginningOfDocumentReachedMessage {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_BeginningOfDocumentReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string FixedDocumentViewers_CaseSensitive {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF (*.pdf)|*.pdf.
        /// </summary>
        public static string FixedDocumentViewers_DialogFilter_PDF {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_DialogFilter_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of the document..
        /// </summary>
        public static string FixedDocumentViewers_EndOfDocumentReachedMessage {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_EndOfDocumentReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FixedDocumentViewers_FindDialogHeader {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FixedDocumentViewers_FindNext {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string FixedDocumentViewers_FindPrevious {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        public static string FixedDocumentViewers_FitWidth {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string FixedDocumentViewers_NavigationPane_Bookmarks {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_NavigationPane_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks: Go to specific points of interest using bookmark links.
        /// </summary>
        public static string FixedDocumentViewers_NavigationPane_BookmarksDescription {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_NavigationPane_BookmarksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find current bookmark.
        /// </summary>
        public static string FixedDocumentViewers_NavigationPane_SyncCurrentBookmark {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_NavigationPane_SyncCurrentBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FixedDocumentViewers_Options {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the document....
        /// </summary>
        public static string FixedDocumentViewers_SearchInTheDocument {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SearchInTheDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one signature is invalid..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePanel_Invalid {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePanel_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one signature has problems..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePanel_Unknown {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePanel_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed and all signatures are valid..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePanel_Valid {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePanel_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Validation Status.
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogHeader {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The document is not modified since this signature was applied..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_IsDocumentModified_False {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_IsDocumentModified_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The document has been altered or corrupted since the Signature was applied..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_IsDocumentModified_True {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_IsDocumentModified_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature is Invalid..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsInvalid {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature validity is Unknown..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsUnknown {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature is Valid, signed by .
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsValid {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignatureIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The signer&apos;s identity is unknown..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_Unknown {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The signer&apos;s identity is unknown because it has not been included in your list of trusted certificates and none of its parent certificates are trusted..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_UntrustedRoot {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_UntrustedR" +
                        "oot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The signer&apos;s identity is valid..
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_Valid {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_SignerValidity_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Signature was validated as of the signing time:.
        /// </summary>
        public static string FixedDocumentViewers_SignaturePropertiesDialogViewModel_Validation_SigningTime {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignaturePropertiesDialogViewModel_Validation_SigningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialog_SelectButton {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialog_SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialog_SignButton {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialog_SignButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Signature.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogHeader {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_AppearanceDateTextFormat {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_AppearanceDateTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitally signed by {0}.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_AppearanceDigitallySignedTextFormat {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_AppearanceDigitallySignedTextFo" +
                        "rmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is invalid or the certificate is corrupted..
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_CertificateOrPasswordError {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_CertificateOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_EnterPassword {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_EnterPasswordError {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_EnterPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX (*.pfx)|*.pfx|All files (*.*)|*.*.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_OpenDialogFilter {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_OpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a PFX certificate.
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_SelectCertificate {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_SelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a PFX certificate..
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_SelectCertificateError {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_SelectCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected certificate does not exist..
        /// </summary>
        public static string FixedDocumentViewers_SignSignatureDialogViewModel_SelectedCertificateDoesNotExists {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SignSignatureDialogViewModel_SelectedCertificateDoesNotExist" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expression.
        /// </summary>
        public static string FixedDocumentViewers_UseRegularExpression {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_UseRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Words Only.
        /// </summary>
        public static string FixedDocumentViewers_WholeWordsOnly {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_WholeWordsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Page Level.
        /// </summary>
        public static string FixedDocumentViewers_ZoomToPageLevel {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_ZoomToPageLevel", resourceCulture);
            }
        }
    }
}
