//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PdfViewerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfViewerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.PdfViewerResources", typeof(PdfViewerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string BusyIndicatorLoading {
            get {
                return ResourceManager.GetString("BusyIndicatorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the beginning of the document..
        /// </summary>
        public static string FixedDocumentViewers_BeginningOfDocumentReachedMessage {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_BeginningOfDocumentReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive.
        /// </summary>
        public static string FixedDocumentViewers_CaseSensitive {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of the document..
        /// </summary>
        public static string FixedDocumentViewers_EndOfDocumentReachedMessage {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_EndOfDocumentReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FixedDocumentViewers_FindDialogHeader {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FixedDocumentViewers_FindNext {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string FixedDocumentViewers_FindPrevious {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Width.
        /// </summary>
        public static string FixedDocumentViewers_FitWidth {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_FitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FixedDocumentViewers_Options {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the document....
        /// </summary>
        public static string FixedDocumentViewers_SearchInTheDocument {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_SearchInTheDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expression.
        /// </summary>
        public static string FixedDocumentViewers_UseRegularExpression {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_UseRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Words Only.
        /// </summary>
        public static string FixedDocumentViewers_WholeWordsOnly {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_WholeWordsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Page Level.
        /// </summary>
        public static string FixedDocumentViewers_ZoomToPageLevel {
            get {
                return ResourceManager.GetString("FixedDocumentViewers_ZoomToPageLevel", resourceCulture);
            }
        }
    }
}
