//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadImageEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadImageEditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.RadImageEditorResources", typeof(RadImageEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        public static string ImageEditor_Adjust {
            get {
                return ResourceManager.GetString("ImageEditor_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ImageEditor_Amount {
            get {
                return ResourceManager.GetString("ImageEditor_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string ImageEditor_Auto {
            get {
                return ResourceManager.GetString("ImageEditor_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        public static string ImageEditor_Background {
            get {
                return ResourceManager.GetString("ImageEditor_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color:.
        /// </summary>
        public static string ImageEditor_BorderColor {
            get {
                return ResourceManager.GetString("ImageEditor_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Thickness:.
        /// </summary>
        public static string ImageEditor_BorderThickness {
            get {
                return ResourceManager.GetString("ImageEditor_BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Resize.
        /// </summary>
        public static string ImageEditor_CanvasResize {
            get {
                return ResourceManager.GetString("ImageEditor_CanvasResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Size.
        /// </summary>
        public static string ImageEditor_CanvasSize {
            get {
                return ResourceManager.GetString("ImageEditor_CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string ImageEditor_ColorPicker_NoColorText_White {
            get {
                return ResourceManager.GetString("ImageEditor_ColorPicker_NoColorText_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string ImageEditor_Crop {
            get {
                return ResourceManager.GetString("ImageEditor_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Text.
        /// </summary>
        public static string ImageEditor_DrawText {
            get {
                return ResourceManager.GetString("ImageEditor_DrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your text here....
        /// </summary>
        public static string ImageEditor_DrawText_YourTextHere {
            get {
                return ResourceManager.GetString("ImageEditor_DrawText_YourTextHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string ImageEditor_DrawTool {
            get {
                return ResourceManager.GetString("ImageEditor_DrawTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Color:.
        /// </summary>
        public static string ImageEditor_DrawTool_BrushColor {
            get {
                return ResourceManager.GetString("ImageEditor_DrawTool_BrushColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Size:.
        /// </summary>
        public static string ImageEditor_DrawTool_BrushSize {
            get {
                return ResourceManager.GetString("ImageEditor_DrawTool_BrushSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string ImageEditor_Effect_Blur {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string ImageEditor_Effect_Brightness {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ImageEditor_Effect_ContrastAdjust {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_ContrastAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Shift.
        /// </summary>
        public static string ImageEditor_Effect_HueShift {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_HueShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Colors.
        /// </summary>
        public static string ImageEditor_Effect_InvertColors {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_InvertColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string ImageEditor_Effect_Saturation {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        public static string ImageEditor_Effect_Sharpen {
            get {
                return ResourceManager.GetString("ImageEditor_Effect_Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string ImageEditor_Effects {
            get {
                return ResourceManager.GetString("ImageEditor_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Horizontal.
        /// </summary>
        public static string ImageEditor_FlipHorizontal {
            get {
                return ResourceManager.GetString("ImageEditor_FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Vertical.
        /// </summary>
        public static string ImageEditor_FlipVertical {
            get {
                return ResourceManager.GetString("ImageEditor_FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string ImageEditor_FontSize {
            get {
                return ResourceManager.GetString("ImageEditor_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string ImageEditor_Height {
            get {
                return ResourceManager.GetString("ImageEditor_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Position.
        /// </summary>
        public static string ImageEditor_HorizontalPosition {
            get {
                return ResourceManager.GetString("ImageEditor_HorizontalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Alignment.
        /// </summary>
        public static string ImageEditor_ImageAlignment {
            get {
                return ResourceManager.GetString("ImageEditor_ImageAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Preview.
        /// </summary>
        public static string ImageEditor_ImagePreview {
            get {
                return ResourceManager.GetString("ImageEditor_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size.
        /// </summary>
        public static string ImageEditor_ImageSize {
            get {
                return ResourceManager.GetString("ImageEditor_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ImageEditor_Open {
            get {
                return ResourceManager.GetString("ImageEditor_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ImageEditor_Options {
            get {
                return ResourceManager.GetString("ImageEditor_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Aspect Ratio.
        /// </summary>
        public static string ImageEditor_PreserveAspectRatio {
            get {
                return ResourceManager.GetString("ImageEditor_PreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius:.
        /// </summary>
        public static string ImageEditor_Radius {
            get {
                return ResourceManager.GetString("ImageEditor_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string ImageEditor_Redo {
            get {
                return ResourceManager.GetString("ImageEditor_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Size.
        /// </summary>
        public static string ImageEditor_RelativeSize {
            get {
                return ResourceManager.GetString("ImageEditor_RelativeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string ImageEditor_Resize {
            get {
                return ResourceManager.GetString("ImageEditor_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 180°.
        /// </summary>
        public static string ImageEditor_Rotate180 {
            get {
                return ResourceManager.GetString("ImageEditor_Rotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 270°.
        /// </summary>
        public static string ImageEditor_Rotate270 {
            get {
                return ResourceManager.GetString("ImageEditor_Rotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90°.
        /// </summary>
        public static string ImageEditor_Rotate90 {
            get {
                return ResourceManager.GetString("ImageEditor_Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string ImageEditor_Rotation {
            get {
                return ResourceManager.GetString("ImageEditor_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Corners.
        /// </summary>
        public static string ImageEditor_RoundCorners {
            get {
                return ResourceManager.GetString("ImageEditor_RoundCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ImageEditor_Save {
            get {
                return ResourceManager.GetString("ImageEditor_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string ImageEditor_Shape {
            get {
                return ResourceManager.GetString("ImageEditor_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string ImageEditor_Shapes_Ellipse {
            get {
                return ResourceManager.GetString("ImageEditor_Shapes_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string ImageEditor_Shapes_Line {
            get {
                return ResourceManager.GetString("ImageEditor_Shapes_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string ImageEditor_Shapes_Rectangle {
            get {
                return ResourceManager.GetString("ImageEditor_Shapes_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Color.
        /// </summary>
        public static string ImageEditor_ShapeTool_BorderColor {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Thickness.
        /// </summary>
        public static string ImageEditor_ShapeTool_BorderThickness {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Shape.
        /// </summary>
        public static string ImageEditor_ShapeTool_FillShape {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_FillShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Ratio.
        /// </summary>
        public static string ImageEditor_ShapeTool_LockRatio {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_LockRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string ImageEditor_ShapeTool_Shape {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Fill.
        /// </summary>
        public static string ImageEditor_ShapeTool_ShapeFill {
            get {
                return ResourceManager.GetString("ImageEditor_ShapeTool_ShapeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ImageEditor_Text {
            get {
                return ResourceManager.GetString("ImageEditor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string ImageEditor_TextColor {
            get {
                return ResourceManager.GetString("ImageEditor_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be opened..
        /// </summary>
        public static string ImageEditor_TheFileCannotBeOpened {
            get {
                return ResourceManager.GetString("ImageEditor_TheFileCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be opened. It might be locked by another application..
        /// </summary>
        public static string ImageEditor_TheFileIsLocked {
            get {
                return ResourceManager.GetString("ImageEditor_TheFileIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string ImageEditor_Transform {
            get {
                return ResourceManager.GetString("ImageEditor_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the file..
        /// </summary>
        public static string ImageEditor_UnableToSaveFile {
            get {
                return ResourceManager.GetString("ImageEditor_UnableToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ImageEditor_Undo {
            get {
                return ResourceManager.GetString("ImageEditor_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format..
        /// </summary>
        public static string ImageEditor_UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("ImageEditor_UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Position.
        /// </summary>
        public static string ImageEditor_VerticalPosition {
            get {
                return ResourceManager.GetString("ImageEditor_VerticalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string ImageEditor_Width {
            get {
                return ResourceManager.GetString("ImageEditor_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
    }
}
