<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MultiSelectionRibbonGallery</RootNamespace>
    <AssemblyName>MultiSelectionRibbonGallery</AssemblyName>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Telerik.UI.for.Wpf.AllControls.Xaml" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\paragraph.png" />
    <Resource Include="Images\paragraph1.png" />
    <Resource Include="Images\paragraph10.png" />
    <Resource Include="Images\paragraph2.png" />
    <Resource Include="Images\paragraph3.png" />
    <Resource Include="Images\paragraph4.png" />
    <Resource Include="Images\paragraph5.png" />
    <Resource Include="Images\paragraph6.png" />
    <Resource Include="Images\paragraph7.png" />
    <Resource Include="Images\paragraph8.png" />
    <Resource Include="Images\paragraph9.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>